In [3]:
import torch
import numpy as np

In [4]:
np_data = np.arange(9).reshape((3,3))
torch_data = torch.from_numpy(np_data)

In [5]:
np_data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
torch_data

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [7]:
#将torch转化成numpy
tensor2numpy = torch_data.numpy()
tensor2numpy

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 常用函数

In [8]:
data = [-1,2,5,-9,-10]
tensor = torch.FloatTensor(data) #将数据转换为32bit浮点数

In [9]:
tensor

tensor([ -1.,   2.,   5.,  -9., -10.])

In [10]:
torch.abs(tensor)

tensor([ 1.,  2.,  5.,  9., 10.])

In [11]:
torch.sin(tensor)

tensor([-0.8415,  0.9093, -0.9589, -0.4121,  0.5440])

In [12]:
torch.mean(tensor)

tensor(-2.6000)

In [16]:
data = np.array([[1,2], [3,4]])
tensor = torch.FloatTensor(data)

In [17]:
np.matmul(data, data) # data.dot(data)

array([[ 7, 10],
       [15, 22]])

In [18]:
torch.mm(tensor, tensor)

tensor([[ 7., 10.],
        [15., 22.]])

In [19]:
data.dot(data)

array([[ 7, 10],
       [15, 22]])