In [1]:
import torch
from torch.autograd import Variable

In [2]:
tensor  =  torch.FloatTensor([[1,2],[3,4]])

In [11]:
variable = Variable(tensor,requires_grad=True) #一般情况下为False，True在梯度下降过程中计算

In [12]:
variable

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [13]:
t_out = torch.mean(tensor * tensor)

In [14]:
t_out

tensor(7.5000)

In [15]:
v_out = torch.mean(variable * variable)

In [16]:
v_out

tensor(7.5000, grad_fn=<MeanBackward0>)

In [17]:
v_out.backward()

In [18]:
variable.grad # 获取ariable的梯度

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [19]:
variable.data

tensor([[1., 2.],
        [3., 4.]])

In [20]:
variable.data.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)